package com.fourgtss.mnp.exception;

public enum PortingRequestErrorCode {
    UNKNOWN_ORGANIZATION,
    MOBILE_NUMBER_NOT_FOUND,
    PORTING_REQUEST_NOT_FOUND,
    NATIONAL_ID_MISMATCH,
    NUMBER_NOT_ACTIVE,
    SAME_OPERATOR,
    MINIMUM_TENURE_NOT_MET,
    PENDING_REQUEST_EXISTS,
    NOT_DONOR,
    DONOR_NO_LONGER_CURRENT,
    REQUEST_NOT_PENDING
}
